/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

(* \nmigen.hierarchy  = "batch_init" *)
(* top =  1  *)
(* generator = "nMigen" *)
module batch_init(a, b);
  (* src = "fakename:1" *)
  output a;
  (* src = "fakename:1" *)
  input b;
  assign a = b;
endmodule
