/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* \nmigen.hierarchy  = "batch_init" *)
(* top =  1  *)
(* generator = "nMigen" *)
module batch_init(a, b);
  (* src = "fakename:1" *)
  output a;
  reg a;
  (* src = "fakename:1" *)
  input b;
  always @* begin
    a = 1'h0;
    a = b;
  end
endmodule
