/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* \nmigen.hierarchy  = "blink" *)
(* top =  1  *)
(* generator = "nMigen" *)
module blink(clk, rst, led);
  (* src = "fakename:6" *)
  wire [24:0] \$1 ;
  (* src = "fakename:6" *)
  wire [24:0] \$2 ;
  (* src = "d:\\iss\\projects\\nmigen\\nmigen\\nmigen\\hdl\\ir.py:526" *)
  input clk;
  (* init = 24'h000000 *)
  (* src = "fakename:3" *)
  reg [23:0] cnt = 24'h000000;
  (* src = "fakename:3" *)
  reg [23:0] \cnt$next ;
  (* src = "fakename:1" *)
  output led;
  reg led;
  (* src = "d:\\iss\\projects\\nmigen\\nmigen\\nmigen\\hdl\\ir.py:526" *)
  input rst;
  assign \$2  = cnt + (* src = "fakename:6" *) 1'h1;
  always @(posedge clk)
      cnt <= \cnt$next ;
  always @* begin
    \cnt$next  = cnt;
    \cnt$next  = \$1 [23:0];
    (* src = "d:\\iss\\projects\\nmigen\\nmigen\\nmigen\\hdl\\xfrm.py:519" *)
    casez (rst)
      1'h1:
          \cnt$next  = 24'h000000;
    endcase
  end
  always @* begin
    led = 1'h0;
    led = cnt[23];
  end
  assign \$1  = \$2 ;
endmodule
