/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

module forced_port(b, c, a);
  input [4:0] a;
  output [4:0] b;
  output [4:0] c;
  assign c = b;
  assign b = a;
endmodule
