/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* \nmigen.hierarchy  = "forced_port" *)
(* top =  1  *)
(* generator = "nMigen" *)
module forced_port(b, c, a);
  (* src = "fakename:1" *)
  input [4:0] a;
  (* src = "fakename:1" *)
  output [4:0] b;
  reg [4:0] b;
  (* src = "fakename:1" *)
  output [4:0] c;
  reg [4:0] c;
  always @* begin
    b = 5'h00;
    b = a;
  end
  always @* begin
    c = 5'h00;
    c = b;
  end
endmodule
