/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

(* \nmigen.hierarchy  = "forced_port" *)
(* top =  1  *)
(* generator = "nMigen" *)
module forced_port(b, c, a);
  (* src = "fakename:3" *)
  input [4:0] a;
  (* src = "fakename:4" *)
  output [4:0] b;
  (* src = "fakename:5" *)
  output [4:0] c;
  assign c = b;
  assign b = a;
endmodule
