/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* \nmigen.hierarchy  = "if_oneliner" *)
(* top =  1  *)
(* generator = "nMigen" *)
module if_oneliner(a, b);
  (* src = "fakename:1" *)
  output a;
  reg a;
  (* src = "fakename:1" *)
  input b;
  always @* begin
    a = 1'h0;
    (* src = "fakename:1" *)
    casez (b)
      /* src = "fakename:1" */
      1'h1:
          a = 1'h1;
      /* src = "fakename:1" */
      default:
          a = 1'h0;
    endcase
  end
endmodule
