/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

module if_oneliner(a, b);
  reg \initial  = 0;
  output a;
  reg a;
  input b;
  always @* begin
    if (\initial ) begin end
    (* full_case = 32'd1 *)
    casez (b)
      1'h1:
          a = 1'h1;
      default:
          a = 1'h0;
    endcase
  end
endmodule
