/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

(* \nmigen.hierarchy  = "if_oneliner" *)
(* top =  1  *)
(* generator = "nMigen" *)
module if_oneliner(a, b);
  reg \initial  = 0;
  (* src = "fakename:1" *)
  output a;
  reg a;
  (* src = "fakename:1" *)
  input b;
  always @* begin
    if (\initial ) begin end
    (* full_case = 32'd1 *)
    (* src = "fakename:5" *)
    casez (b)
      /* src = "fakename:5" */
      1'h1:
          a = 1'h1;
      /* src = "fakename:1" */
      default:
          a = 1'h0;
    endcase
  end
endmodule
