/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

(* \nmigen.hierarchy  = "indexing" *)
(* top =  1  *)
(* generator = "nMigen" *)
module indexing(outp, clk, rst, inp);
  reg \initial  = 0;
  (* src = "fakename:6" *)
  wire \$signal ;
  (* src = "fakename:6" *)
  wire \$signal$1 ;
  (* src = "fakename:6" *)
  wire \$signal$10 ;
  (* src = "fakename:6" *)
  wire \$signal$11 ;
  (* src = "fakename:6" *)
  wire \$signal$12 ;
  (* src = "fakename:6" *)
  wire \$signal$13 ;
  (* src = "fakename:6" *)
  wire \$signal$14 ;
  (* src = "fakename:6" *)
  wire \$signal$15 ;
  (* src = "fakename:6" *)
  wire \$signal$16 ;
  (* src = "fakename:6" *)
  wire \$signal$17 ;
  (* src = "fakename:6" *)
  wire \$signal$18 ;
  (* src = "fakename:6" *)
  wire \$signal$19 ;
  (* src = "fakename:6" *)
  wire \$signal$2 ;
  (* src = "fakename:6" *)
  wire \$signal$20 ;
  (* src = "fakename:6" *)
  wire \$signal$21 ;
  (* src = "fakename:6" *)
  wire \$signal$22 ;
  (* src = "fakename:6" *)
  wire \$signal$23 ;
  (* src = "fakename:6" *)
  wire \$signal$24 ;
  (* src = "fakename:6" *)
  wire \$signal$25 ;
  (* src = "fakename:6" *)
  wire \$signal$26 ;
  (* src = "fakename:7" *)
  reg \$signal$27  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$27$next ;
  (* src = "fakename:7" *)
  reg \$signal$28  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$28$next ;
  (* src = "fakename:7" *)
  reg \$signal$29  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$29$next ;
  (* src = "fakename:6" *)
  wire \$signal$3 ;
  (* src = "fakename:7" *)
  reg \$signal$30  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$30$next ;
  (* src = "fakename:7" *)
  reg \$signal$31  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$31$next ;
  (* src = "fakename:7" *)
  reg \$signal$32  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$32$next ;
  (* src = "fakename:7" *)
  reg \$signal$33  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$33$next ;
  (* src = "fakename:7" *)
  reg \$signal$34  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$34$next ;
  (* src = "fakename:7" *)
  reg \$signal$35  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$35$next ;
  (* src = "fakename:7" *)
  reg \$signal$36  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$36$next ;
  (* src = "fakename:7" *)
  reg \$signal$37  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$37$next ;
  (* src = "fakename:7" *)
  reg \$signal$38  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$38$next ;
  (* src = "fakename:7" *)
  reg \$signal$39  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$39$next ;
  (* src = "fakename:6" *)
  wire \$signal$4 ;
  (* src = "fakename:7" *)
  reg \$signal$40  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$40$next ;
  (* src = "fakename:7" *)
  reg \$signal$41  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$41$next ;
  (* src = "fakename:7" *)
  reg \$signal$42  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$42$next ;
  (* src = "fakename:7" *)
  reg \$signal$43  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$43$next ;
  (* src = "fakename:7" *)
  reg \$signal$44  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$44$next ;
  (* src = "fakename:7" *)
  reg \$signal$45  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$45$next ;
  (* src = "fakename:7" *)
  reg \$signal$46  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$46$next ;
  (* src = "fakename:7" *)
  reg \$signal$47  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$47$next ;
  (* src = "fakename:7" *)
  reg \$signal$48  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$48$next ;
  (* src = "fakename:7" *)
  reg \$signal$49  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$49$next ;
  (* src = "fakename:6" *)
  wire \$signal$5 ;
  (* src = "fakename:7" *)
  reg \$signal$50  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$50$next ;
  (* src = "fakename:7" *)
  reg \$signal$51  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$51$next ;
  (* src = "fakename:7" *)
  reg \$signal$52  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$52$next ;
  (* src = "fakename:7" *)
  reg \$signal$53  = 1'h0;
  (* src = "fakename:7" *)
  reg \$signal$53$next ;
  (* src = "fakename:6" *)
  wire \$signal$6 ;
  (* src = "fakename:6" *)
  wire \$signal$7 ;
  (* src = "fakename:6" *)
  wire \$signal$8 ;
  (* src = "fakename:6" *)
  wire \$signal$9 ;
  (* src = "/home/pi/repos/nmigen/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "fakename:4" *)
  input [26:0] inp;
  (* src = "fakename:5" *)
  output [26:0] outp;
  (* src = "/home/pi/repos/nmigen/nmigen/hdl/ir.py:526" *)
  input rst;
  always @(posedge clk)
    \$signal$53  <= \$signal$53$next ;
  always @(posedge clk)
    \$signal$44  <= \$signal$44$next ;
  always @(posedge clk)
    \$signal$43  <= \$signal$43$next ;
  always @(posedge clk)
    \$signal$42  <= \$signal$42$next ;
  always @(posedge clk)
    \$signal$41  <= \$signal$41$next ;
  always @(posedge clk)
    \$signal$40  <= \$signal$40$next ;
  always @(posedge clk)
    \$signal$39  <= \$signal$39$next ;
  always @(posedge clk)
    \$signal$38  <= \$signal$38$next ;
  always @(posedge clk)
    \$signal$37  <= \$signal$37$next ;
  always @(posedge clk)
    \$signal$36  <= \$signal$36$next ;
  always @(posedge clk)
    \$signal$35  <= \$signal$35$next ;
  always @(posedge clk)
    \$signal$52  <= \$signal$52$next ;
  always @(posedge clk)
    \$signal$34  <= \$signal$34$next ;
  always @(posedge clk)
    \$signal$33  <= \$signal$33$next ;
  always @(posedge clk)
    \$signal$32  <= \$signal$32$next ;
  always @(posedge clk)
    \$signal$31  <= \$signal$31$next ;
  always @(posedge clk)
    \$signal$30  <= \$signal$30$next ;
  always @(posedge clk)
    \$signal$29  <= \$signal$29$next ;
  always @(posedge clk)
    \$signal$28  <= \$signal$28$next ;
  always @(posedge clk)
    \$signal$27  <= \$signal$27$next ;
  always @(posedge clk)
    \$signal$51  <= \$signal$51$next ;
  always @(posedge clk)
    \$signal$50  <= \$signal$50$next ;
  always @(posedge clk)
    \$signal$49  <= \$signal$49$next ;
  always @(posedge clk)
    \$signal$48  <= \$signal$48$next ;
  always @(posedge clk)
    \$signal$47  <= \$signal$47$next ;
  always @(posedge clk)
    \$signal$46  <= \$signal$46$next ;
  always @(posedge clk)
    \$signal$45  <= \$signal$45$next ;
  always @* begin
    if (\initial ) begin end
    \$signal$27$next  = \$signal ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$27$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$28$next  = \$signal$3 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$28$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$29$next  = \$signal$6 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$29$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$30$next  = \$signal$9 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$30$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$31$next  = \$signal$12 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$31$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$32$next  = \$signal$15 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$32$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$33$next  = \$signal$18 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$33$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$34$next  = \$signal$21 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$34$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$35$next  = \$signal$24 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$35$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$36$next  = \$signal$1 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$36$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$37$next  = \$signal$4 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$37$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$38$next  = \$signal$7 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$38$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$39$next  = \$signal$10 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$39$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$40$next  = \$signal$13 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$40$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$41$next  = \$signal$16 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$41$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$42$next  = \$signal$19 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$42$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$43$next  = \$signal$22 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$43$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$44$next  = \$signal$25 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$44$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$45$next  = \$signal$2 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$45$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$46$next  = \$signal$5 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$46$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$47$next  = \$signal$8 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$47$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$48$next  = \$signal$11 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$48$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$49$next  = \$signal$14 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$49$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$50$next  = \$signal$17 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$50$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$51$next  = \$signal$20 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$51$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$52$next  = \$signal$23 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$52$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \$signal$53$next  = \$signal$26 ;
    (* src = "/home/pi/repos/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \$signal$53$next  = 1'h0;
    endcase
  end
  assign outp = { \$signal$53 , \$signal$52 , \$signal$51 , \$signal$50 , \$signal$49 , \$signal$48 , \$signal$47 , \$signal$46 , \$signal$45 , \$signal$44 , \$signal$43 , \$signal$42 , \$signal$41 , \$signal$40 , \$signal$39 , \$signal$38 , \$signal$37 , \$signal$36 , \$signal$35 , \$signal$34 , \$signal$33 , \$signal$32 , \$signal$31 , \$signal$30 , \$signal$29 , \$signal$28 , \$signal$27  };
  assign \$signal$26  = inp[26];
  assign \$signal$25  = inp[25];
  assign \$signal$24  = inp[24];
  assign \$signal$23  = inp[23];
  assign \$signal$22  = inp[22];
  assign \$signal$21  = inp[21];
  assign \$signal$20  = inp[20];
  assign \$signal$19  = inp[19];
  assign \$signal$18  = inp[18];
  assign \$signal$17  = inp[17];
  assign \$signal$16  = inp[16];
  assign \$signal$15  = inp[15];
  assign \$signal$14  = inp[14];
  assign \$signal$13  = inp[13];
  assign \$signal$12  = inp[12];
  assign \$signal$11  = inp[11];
  assign \$signal$10  = inp[10];
  assign \$signal$9  = inp[9];
  assign \$signal$8  = inp[8];
  assign \$signal$7  = inp[7];
  assign \$signal$6  = inp[6];
  assign \$signal$5  = inp[5];
  assign \$signal$4  = inp[4];
  assign \$signal$3  = inp[3];
  assign \$signal$2  = inp[2];
  assign \$signal$1  = inp[1];
  assign \$signal  = inp[0];
endmodule
