/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* \nmigen.hierarchy  = "indirect_sink_source_relation" *)
(* top =  1  *)
(* generator = "nMigen" *)
module indirect_sink_source_relation(b, a);
  (* src = "fakename:1" *)
  input a;
  (* src = "fakename:1" *)
  output b;
  reg b;
  (* src = "fakename:1" *)
  reg v;
  always @* begin
    v = 1'h0;
    v = a;
  end
  always @* begin
    b = 1'h0;
    b = v;
  end
endmodule
