/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

module indirect_sink_source_relation(b, a);
  input a;
  output b;
  wire v;
  assign b = v;
  assign v = a;
endmodule
