/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

(* \nmigen.hierarchy  = "indirect_sink_source_relation" *)
(* top =  1  *)
(* generator = "nMigen" *)
module indirect_sink_source_relation(b, a);
  (* src = "fakename:1" *)
  input a;
  (* src = "fakename:1" *)
  output b;
  (* src = "fakename:1" *)
  wire v;
  assign b = v;
  assign v = a;
endmodule
