/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

module inherit_width_from_slicing(clk, rst, led);
  reg \initial  = 0;
  wire [24:0] \$1 ;
  wire [24:0] \$2 ;
  input clk;
  reg [23:0] cnt = 24'h000000;
  reg [23:0] \cnt$next ;
  output led;
  input rst;
  assign \$2  = cnt + 1'h1;
  always @(posedge clk)
    cnt <= \cnt$next ;
  always @* begin
    if (\initial ) begin end
    \cnt$next  = \$1 [23:0];
    casez (rst)
      1'h1:
          \cnt$next  = 24'h000000;
    endcase
  end
  assign \$1  = \$2 ;
  assign led = cnt[23];
endmodule
