/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* \nmigen.hierarchy  = "no_main_call" *)
(* top =  1  *)
(* generator = "nMigen" *)
module no_main_call(b, a);
  (* src = "fakename:1" *)
  input a;
  (* src = "fakename:1" *)
  output b;
  reg b;
  always @* begin
    b = 1'h0;
    b = a;
  end
endmodule
