/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

(* \nmigen.hierarchy  = "no_main_call" *)
(* top =  1  *)
(* generator = "nMigen" *)
module no_main_call(b, a);
  (* src = "fakename:1" *)
  input a;
  (* src = "fakename:1" *)
  output b;
  assign b = a;
endmodule
