/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* \nmigen.hierarchy  = "python_const" *)
(* top =  1  *)
(* generator = "nMigen" *)
module python_const(o);
  (* init = 1'h0 *)
  reg \$verilog_initial_trigger  = 1'h0;
  (* src = "fakename:1" *)
  output [31:0] o;
  reg [31:0] o;
  always @* begin
    o = 32'd0;
    o = 32'd12345;
    \$verilog_initial_trigger  = \$verilog_initial_trigger ;
  end
endmodule
