/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

(* \nmigen.hierarchy  = "python_const" *)
(* top =  1  *)
(* generator = "nMigen" *)
module python_const(o);
  (* src = "fakename:3" *)
  output [31:0] o;
  assign o = 32'd12345;
endmodule
