/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

(* \nmigen.hierarchy  = "simple_inheritance" *)
(* top =  1  *)
(* generator = "nMigen" *)
module simple_inheritance(inv, outs, outv, ins);
  (* src = "fakename:1" *)
  input ins;
  (* src = "fakename:4" *)
  input [31:0] inv;
  (* src = "fakename:1" *)
  output outs;
  (* src = "fakename:4" *)
  output [31:0] outv;
  assign outv = inv;
  assign outs = ins;
endmodule
