/* Generated by Yosys 0.9+3833 (git sha1 b0004911, clang 7.0.1-8+rpi3+deb10u2 -fPIC -Os) */

module simple_inheritance(inv, outs, outv, ins);
  input ins;
  input [31:0] inv;
  output outs;
  output [31:0] outv;
  assign outv = inv;
  assign outs = ins;
endmodule
