/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* \nmigen.hierarchy  = "simple_inheritance" *)
(* top =  1  *)
(* generator = "nMigen" *)
module simple_inheritance(inv, outs, outv, ins);
  (* src = "fakename:1" *)
  input ins;
  (* src = "fakename:1" *)
  input [31:0] inv;
  (* src = "fakename:1" *)
  output outs;
  reg outs;
  (* src = "fakename:1" *)
  output [31:0] outv;
  reg [31:0] outv;
  always @* begin
    outs = 1'h0;
    outs = ins;
  end
  always @* begin
    outv = 32'd0;
    outv = inv;
  end
endmodule
